# Generated by Django 6.0.6 on 2026-06-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('categoria_estrellas', models.IntegerField()),
                ('sitio_web', models.URLField(max_length=255)),
                ('logo_url', models.URLField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('hora_check_in', models.TimeField()),
                ('hora_check_out', models.TimeField()),
                ('permite_mascotas', models.BooleanField(default=False)),
                ('edad_minima_reserva', models.IntegerField()),
                ('politica_cancelacion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hotel',
            },
        ),
    ]
