# Generated by Django 6.0.6 on 2026-07-13 14:59

import hotel_app.models.imagen_habitacion
import hotel_app.models.perfil_usuario
import hotel_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenhabitacion',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Imagen de Habitación', 'verbose_name_plural': 'Imágenes de Habitación'},
        ),
        migrations.AlterField(
            model_name='imagenhabitacion',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='imagenhabitacion',
            name='imagen_url',
            field=models.ImageField(max_length=255, upload_to=hotel_app.models.imagen_habitacion.habitacion_image_upload_path, validators=[hotel_app.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='imagenhabitacion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=hotel_app.models.perfil_usuario.profile_image_upload_path, validators=[hotel_app.validators.validate_image_file]),
        ),
    ]
