# Generated by Django 6.0.6 on 2026-07-14 13:35

import hotel_app.models.hotel
import hotel_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_imagenhabitacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=hotel_app.models.hotel.hotel_logo_upload_path, validators=[hotel_app.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sitio_web',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
