# Generated by Django 6.0.6 on 2026-06-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_direccionhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('capacidad_adultos', models.IntegerField()),
                ('capacidad_ninos', models.IntegerField()),
                ('capacidad_total', models.IntegerField()),
                ('tamano_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_habitacion', to='hotel_app.hotel')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
                'db_table': 'tipo_habitacion',
            },
        ),
    ]
