# Generated by Django 6.0.6 on 2026-06-28 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_cama'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacionCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_habitacion', to='hotel_app.cama')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='hotel_app.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Cama por Tipo de Habitación',
                'verbose_name_plural': 'Camas por Tipo de Habitación',
                'db_table': 'tipo_habitacion_cama',
            },
        ),
    ]
