# Generated by Django 6.0.6 on 2026-06-28 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_tipohabitacioncama'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(max_length=255)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('es_principal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='hotel_app.habitacion')),
            ],
            options={
                'verbose_name': 'Imagen de Habitación',
                'verbose_name_plural': 'Imágenes de Habitación',
                'db_table': 'imagen_habitacion',
            },
        ),
    ]
