# Generated by Django 6.0.6 on 2026-07-21 22:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_pago_factura_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='detalle_lineas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reserva',
            name='subtotal_habitaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reserva',
            name='subtotal_servicios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='hotel_app.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_servicio', to='hotel_app.servicio')),
            ],
            options={
                'verbose_name': 'Servicio de reserva',
                'verbose_name_plural': 'Servicios de reserva',
                'db_table': 'reserva_servicio',
                'ordering': ['id'],
                'unique_together': {('reserva', 'servicio')},
            },
        ),
    ]
